[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ntop"
version = "0.1.0"
description = "Neural topology analysis"
authors = [{name = "Neural Topology Team"}]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "torch>=2.0.0",
    "numpy>=1.21.0",
    "matplotlib>=3.5.0",
    "scikit-learn>=1.1.0",
    "ripser>=0.6.0",
]

[project.optional-dependencies]
extra = [
    "pot>=0.9.0",
    "seaborn>=0.11.0",
]

[tool.setuptools.packages.find]
include = ["ntop*"]