[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ntop"
version = "0.0.0a1"
description = "ntop"
authors = [{name = "Jacob Molnia", email = "jrmolnia@wpi.edu"}]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.0.0",
    "numpy>=1.21.0",
    "matplotlib>=3.5.0",
    "scikit-learn>=1.1.0",
    "ripser>=0.6.0",
    "seaborn>=0.11.0",
    "tinyzoo @ git+https://github.com/jake-molnia/tinyzoo.git",
    "click>=8.2.1",
    "tqdm>=4.67.1",
    "transformers>=4.56.1",
]

[project.optional-dependencies]
extra = [
    "pot>=0.9.0",
]

[tool.setuptools.packages.find]
include = ["ntop*"]
