# This file defines a grid of experiments. The script will run all combinations
# of models and ablation strategies defined below.

# ----------------------------------------------------------------------
# 1. COMMON SETTINGS
# These settings apply to all generated experiments.
# ----------------------------------------------------------------------
base_config:
  description: "Grid search over MLP models and various topological/geometric ablation strategies."
  tags: ["MLP", "grid_search", "MNIST", "topological_ablation"]
  seed: 42
  dataset:
    name: "MNIST"
    path: "./data"
    batch_size: 128
    num_workers: 4
  training:
    enabled: true
    epochs: 15
    optimizer:
      name: "Adam"
      params:
        lr: 0.001
    lr_scheduler:
      name: "StepLR"
      params:
        step_size: 7
        gamma: 0.1
  analysis:
    activation_extraction:
      layers: ["layer1", "layer2", "layer3"] # Layers to form the global neuron space
      dataset_split: "train"
      max_samples: 100000 # Use 10k samples from the test set for analysis
      normalize_activations: false # New flag for normalization
      normalization_method: "none" # Options: "standard", "minmax", "none"
    visualizations:
      tsne_plot: false # Disable expensive plots for faster suite runs
      distance_matrix: true
      persistence_diagram: false # Keep this to verify topological calculations
  outputs:
    base_dir: "./experiment_grid" # Use a new directory for grid results
    save_model_checkpoint: true
    save_activations: false
    save_results_csv: true

# ----------------------------------------------------------------------
# 2. EXPERIMENT AXES
# The script will generate the Cartesian product of these lists.
# ----------------------------------------------------------------------

# --- AXIS 1: Models ---
# Defines the different model architectures to test.
models:
  - name: "MLP_BN-False_Drop-0.3"
    architecture: "MNIST_MLP"
    params:
      use_batchnorm: false
      dropout_rate: 0.3

# --- AXIS 2: Ablation Strategies ---
# Defines the different neuron removal strategies to test for each model.
ablations:
  # --- New Topological Strategies ---
  #- strategy: "homology_persistence"
  #  params:
  #    homology_persistence:
  #      homology_dim: 1 # Filter based on the lifetime of 1D loops

  - strategy: "homology_degree_H0"
    params:
      homology_degree:
        homology_dim: 0 # Filter based on importance to 1D loops
  - strategy: "homology_degree_H1"
    params:
      homology_degree:
        homology_dim: 1 # Filter based on importance to 1D loops
  - strategy: "homology_degree_H2"
    params:
      homology_degree:
        homology_dim: 2 # Filter based on importance to 1D loops
  # --- Baseline Strategies ---
  - strategy: "random"
    params: {} # No parameters needed for random