# configs/advanced_config.yaml
# Configuration for the advanced topological analysis pipeline.

run_name: "Advanced_Analysis_MNIST_MLP"

# --- Model & Data ---
# Specify the path to a pre-trained model checkpoint from a 01_run_experiment run.
model_checkpoint: "./experiments/YOUR_EXPERIMENT_RUN_NAME/model.pth"
dataset: "MNIST"
data_path: "./data"
batch_size: 1000

# --- Analysis Parameters ---
# Layer to perform the main analysis on.
layer_to_analyze: "fc2"

# Maximum number of data samples to use for activation extraction.
# null means use the whole dataset.
max_samples: 5000 

# Normalization for activations ('standard', 'minmax', 'none')
# 'standard' is generally recommended for distance-based analyses.
normalization_method: "standard"

# --- Multi-Scale Analysis ---
# Number of filtration scales to use for criticality analysis.
num_filtration_scales: 15

# --- Hybrid Analysis ---
# Set to true to compute gradient-based importance as well.
compute_gradient_importance: true

# --- Device ---
device: "mps" # or "cuda" if available
